import React from 'react';
import Link from 'next/link';
export var Footer = function () { return (React.createElement("div", { className: "bg-black text-white" },
    React.createElement("div", { className: "sm:flex container mx-auto max-w-lg" },
        React.createElement("div", { className: "border-r text-start border-white px-2 py-8 sm:w-1/4" },
            React.createElement("h3", { className: "text-yellow mb-2" }, "Samarbejdspartnere "),
            React.createElement("ul", { className: "list-reset leading-normal" },
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.sn.dk", className: "white", target: "_blank" }, "Dagbladet")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://frdb.dk/", className: "white", target: "_blank" }, "Fredericia Dagblad")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.sn.dk", className: "white", target: "_blank" }, "Frederiksborg Amts Avis")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.fyens.dk", className: "white", target: "_blank" }, "Fyens Stiftstidende")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.faa.dk", className: "white", target: "_blank" }, "Fyns Amts Avis")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://hsfo.dk/", className: "white", target: "_blank" }, "Horsens Folkeblad")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.jv.dk", className: "white", target: "_blank" }, "Jydske Vestkysten")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://nordjyske.dk/", className: "white", target: "_blank" }, "Nordjyske")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.nordvestnyt.dk", className: "white", target: "_blank" }, "Nordvestnyt")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://amtsavisen.dk/", className: "white", target: "_blank" }, "Randers Amtsavis")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.sn.dk", className: "white", target: "_blank" }, "Sj\u00E6llandske")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.thisted-dagblad.dk", className: "white", target: "_blank" }, "Thisted Dagblad")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://www.vafo.dk", className: "white", target: "_blank" }, "Vejle Amts Folkeblad")),
                React.createElement("li", null,
                    React.createElement("a", { href: "http://stiften.dk", className: "white", target: "_blank" }, "\u00C5rhus Stiftstidende")))),
        React.createElement("div", { className: "border-r text-start border-white px-2 py-8 sm:w-1/4" },
            React.createElement("h3", { className: "text-yellow mb-2" }, "GulogGratis.dk"),
            React.createElement("ul", { className: "list-reset leading-normal" },
                React.createElement("li", null,
                    React.createElement("a", { href: "https://mit.guloggratis.dk/pakkepost", className: "white" }, "Pakkepost")),
                React.createElement("li", null,
                    React.createElement("a", { href: "https://itunes.apple.com/dk/app/guloggratis/id599906021?mt=8", className: "white", target: "_blank" }, "iPhone App")),
                React.createElement("li", null,
                    React.createElement("a", { href: "https://m.guloggratis.dk?disable_adaptive=false", className: "white" }, "Mobilvenlig GulogGratis.dk")),
                React.createElement("li", null,
                    React.createElement("a", { href: "/sider/information", className: "white" }, "Information")),
                React.createElement("li", null,
                    React.createElement("a", { href: "/sider/brugerbetingelser", className: "white" }, "Betingelser")),
                React.createElement("li", null,
                    React.createElement(Link, { href: "/sider/privatlivspolitik" },
                        React.createElement("a", { className: "white" }, "Cookiepolitik"))),
                React.createElement("li", null,
                    React.createElement(Link, { href: "/sider/erhvervsannoncering" },
                        React.createElement("a", { className: "white" }, "Erhvervsannoncering"))),
                React.createElement("li", null,
                    React.createElement(Link, { href: "/sitemap" },
                        React.createElement("a", { className: "white" }, "Sitemap"))))),
        React.createElement("div", { className: "px-2 py-8 w-1/2" },
            React.createElement("div", { className: "flex justify-between" },
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-yellow  mb-2" }, "Support"),
                    React.createElement("ul", { className: "list-reset" },
                        React.createElement("li", null,
                            React.createElement(Link, { href: "/support" },
                                React.createElement("a", { className: "white" }, "Kontakt support"))))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-yellow" }, "GulogGratis.dk p\u00E5 sociale medier"))))))); };
